package restore

import (
	apis "github.com/openebs/maya/pkg/apis/openebs.io/restore/v1alpha1"
	"github.com/openebs/maya/pkg/client/generated/openebs.io/restore/v1alpha1/clientset/internalclientset"
	"github.com/pkg/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/rest"
)

// KubeClient is the kubernetes restore client to perform
// operation on restore CR
type KubeClient struct {
	// client is a restore custom resource package generated for custom API group.
	client internalclientset.Interface
}

// CStorRestore describes a cstor restore object created for restore operation
type CStorRestore struct {
	// KubeClient to perform operation on restore CR
	*KubeClient

	// object is restore API object
	object *apis.CStorRestore
}

// CStorRestoreBuilder defines builder for CStorRestore
type CStorRestoreBuilder struct {
	// restorename represents restore name
	restorename string

	// volumename represensts volume name on which restore will be performed
	volumename string

	// restoresrc is restore destination
	restoresrc string

	// namespace is current restore namespace
	namespace string

	// maxretrycount is max number of retry, cstor-volume-mgmt should perform if restore fails
	maxretrycount int

	// obj is CStorRestore api object
	obj *CStorRestore

	// predicatelist is list of predicate function used for validating object
	predicatelist []PredicateFunc

	// err is used to store error generated during object build operation
	err error
}

// LoadRestoreClient defines data-type for kubeclient load function
type LoadRestoreClient func() (internalclientset.Interface, error)

// NewCStorRestoreBuilder returns new CStorRestore builder
func NewCStorRestoreBuilder() *CStorRestoreBuilder {
	return &CStorRestoreBuilder{
		obj: &CStorRestore{
			KubeClient: &KubeClient{},
		},
	}
}

// WithRestoreName set restore-name for current builder
func (cr *CStorRestoreBuilder) WithRestoreName(restorename string) *CStorRestoreBuilder {
	cr.restorename = restorename
	return cr
}

// WithVolumeName set volume-name for current builder
func (cr *CStorRestoreBuilder) WithVolumeName(volumename string) *CStorRestoreBuilder {
	cr.volumename = volumename
	return cr
}

// WithRestoreSrc set restore source for current builder
func (cr *CStorRestoreBuilder) WithRestoreSrc(restoresrc string) *CStorRestoreBuilder {
	cr.restoresrc = restoresrc
	return cr
}

// WithMaxRetryCount set max retry count for current builder
func (cr *CStorRestoreBuilder) WithMaxRetryCount(maxcount int) *CStorRestoreBuilder {
	cr.maxretrycount = maxcount
	return cr
}

// WithNameSpace set namespace for current builder
func (cr *CStorRestoreBuilder) WithNameSpace(namespace string) *CStorRestoreBuilder {
	cr.namespace = namespace
	return cr
}

// WithCheck appends then given filter to current builder's filter list
func (cr *CStorRestoreBuilder) WithCheck(pred ...PredicateFunc) *CStorRestoreBuilder {
	cr.predicatelist = append(cr.predicatelist, pred...)
	return cr
}

// WithCheckList appends the given filter list to current builder's filter list
func (cr *CStorRestoreBuilder) WithCheckList(pred []PredicateFunc) *CStorRestoreBuilder {
	cr.predicatelist = append(cr.predicatelist, pred...)
	return cr
}

// WithClientSet loads the kubeclient either by given function or default function
func (cr *CStorRestoreBuilder) WithClientSet(fn LoadRestoreClient) *CStorRestoreBuilder {
	var err error
	var restoreclient internalclientset.Interface

	if fn != nil {
		restoreclient, err = fn()
	} else {
		restoreclient, err = LoadClientSet()
	}

	if err == nil {
		cr.obj.client = restoreclient
	} else {
		errors.Wrapf(cr.err, "Failed to fetch clientset : %s", err.Error())
	}
	return cr
}

// LoadClientSet load restore client from cluster config
func LoadClientSet() (internalclientset.Interface, error) {
	cfg, err := rest.InClusterConfig()
	if err != nil {
		return nil, err
	}

	return internalclientset.NewForConfig(cfg)
}

// Build returns the CStorRestore object generated by current builder
func (cr *CStorRestoreBuilder) Build() (*CStorRestore, error) {
	cr.obj.object = &apis.CStorRestore{
		ObjectMeta: metav1.ObjectMeta{
			Namespace: cr.namespace,
		},
		Spec: apis.CStorRestoreSpec{
			RestoreName:   cr.restorename,
			VolumeName:    cr.volumename,
			RestoreSrc:    cr.restoresrc,
			MaxRetryCount: cr.maxretrycount,
		},
	}

	cr.obj.SetObjName()

	cr = cr.Validate()
	return cr.obj, cr.err
}

// BuildFromAPIObject generates the CStorRestore object using given api object
func (cr *CStorRestoreBuilder) BuildFromAPIObject(obj *apis.CStorRestore) (*CStorRestore, error) {
	cr.obj.object = obj.DeepCopy()
	cr = cr.Validate()
	return cr.obj, cr.err
}

// BuildFromAPIObjectName generates the CStorRestore object for given object name
func (cr *CStorRestoreBuilder) BuildFromAPIObjectName(name string) (*CStorRestore, error) {
	obj, err := cr.obj.Get(name, cr.namespace)
	if err == nil {
		cr.obj.object = obj
		cr = cr.Validate()
	} else {
		errors.Wrapf(cr.err, "Failed to fetch restore{%s} : %s", name, err.Error())
	}
	return cr.obj, cr.err
}

// Validate is to validate generated CStorRestore object by current builder
func (cr *CStorRestoreBuilder) Validate() *CStorRestoreBuilder {
	if len(cr.predicatelist) != 0 {
		for _, pred := range cr.predicatelist {
			if !pred(cr.obj) {
				errors.Wrapf(cr.err, "Predicate{%v} Failed", pred)
			}
		}
	}
	return cr
}
