package backup

import (
	apis "github.com/openebs/maya/pkg/apis/openebs.io/backup/v1alpha1"
	"github.com/openebs/maya/pkg/client/generated/openebs.io/backup/v1alpha1/clientset/internalclientset"
	"github.com/pkg/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/rest"
)

// KubeClient is the kubernetes backup client to perform
// operation on backup CR
type KubeClient struct {
	// client is a backup custom resource package generated for custom API group.
	client internalclientset.Interface
}

// CStorBackup describes a cstor backup object created for backup operation
type CStorBackup struct {
	// KubeClient to perform operation on backup CR
	*KubeClient

	// object is backup API object
	object *apis.CStorBackup
}

// CStorBackupBuilder defines builder for CStorBackup
type CStorBackupBuilder struct {
	// backupname represents backup name
	backupname string

	// volumename represensts volume name on which backup will be performed
	volumename string

	// snapname is snapshot name for current backup
	snapname string

	// prevsnapname is snapshot name from last sucessfull backup
	prevsnapname string

	// backupdest is backup destination
	backupdest string

	// namespace is current backup namespace
	namespace string

	// obj is CStorBackup api object
	obj *CStorBackup

	// predicatelist is list of predicate function used for validating object
	predicatelist []PredicateFunc

	// err is used to store error generated during object build operation
	err error
}

// LoadBackupClient defines data-type for kubeclient load function
type LoadBackupClient func() (internalclientset.Interface, error)

// NewCStorBackupBuilder returns new CStorBackup builder
func NewCStorBackupBuilder() *CStorBackupBuilder {
	return &CStorBackupBuilder{
		obj: &CStorBackup{
			KubeClient: &KubeClient{},
		},
	}
}

// WithBackupName set backup-name for current builder
func (cb *CStorBackupBuilder) WithBackupName(backupname string) *CStorBackupBuilder {
	cb.backupname = backupname
	return cb
}

// WithVolumeName set volume-name for current builder
func (cb *CStorBackupBuilder) WithVolumeName(volumename string) *CStorBackupBuilder {
	cb.volumename = volumename
	return cb
}

// WithSnapName set snapshot-name for current builder
func (cb *CStorBackupBuilder) WithSnapName(snapname string) *CStorBackupBuilder {
	cb.snapname = snapname
	return cb
}

// WithPrevSnapName set previous snapshot name for current builder
func (cb *CStorBackupBuilder) WithPrevSnapName(prevsnapname string) *CStorBackupBuilder {
	cb.prevsnapname = prevsnapname
	return cb
}

// WithBackupDest set backup destination for current builder
func (cb *CStorBackupBuilder) WithBackupDest(backupdest string) *CStorBackupBuilder {
	cb.backupdest = backupdest
	return cb
}

// WithNameSpace set namespace for current builder
func (cb *CStorBackupBuilder) WithNameSpace(namespace string) *CStorBackupBuilder {
	cb.namespace = namespace
	return cb
}

// WithCheck appends then given filter to current builder's filter list
func (cb *CStorBackupBuilder) WithCheck(pred ...PredicateFunc) *CStorBackupBuilder {
	cb.predicatelist = append(cb.predicatelist, pred...)
	return cb
}

// WithCheckList appends the given filter list to current builder's filter list
func (cb *CStorBackupBuilder) WithCheckList(pred []PredicateFunc) *CStorBackupBuilder {
	cb.predicatelist = append(cb.predicatelist, pred...)
	return cb
}

// WithClientSet loads the kubeclient either by given function or default function
func (cb *CStorBackupBuilder) WithClientSet(fn LoadBackupClient) *CStorBackupBuilder {
	var err error
	var backupclient internalclientset.Interface

	if fn != nil {
		backupclient, err = fn()
	} else {
		backupclient, err = LoadClientSet()
	}

	if err == nil {
		cb.obj.client = backupclient
	} else {
		errors.Wrapf(cb.err, "Failed to load clientset : %s", err)
	}

	return cb
}

// LoadClientSet load backup client from cluster config
func LoadClientSet() (internalclientset.Interface, error) {
	cfg, err := rest.InClusterConfig()
	if err != nil {
		return nil, err
	}

	return internalclientset.NewForConfig(cfg)
}

// Build returns the CStorBakup object generated by current builder
func (cb *CStorBackupBuilder) Build() (*CStorBackup, error) {
	cb.obj.object = &apis.CStorBackup{
		ObjectMeta: metav1.ObjectMeta{
			Name:      cb.snapname + "-" + cb.volumename,
			Namespace: cb.namespace,
		},
		Spec: apis.CStorBackupSpec{
			BackupName:   cb.backupname,
			VolumeName:   cb.volumename,
			SnapName:     cb.snapname,
			PrevSnapName: cb.prevsnapname,
			BackupDest:   cb.backupdest,
		},
	}
	cb = cb.Validate()
	return cb.obj, cb.err
}

// BuildFromAPIObject generates the CStorBackup object using given api object
func (cb *CStorBackupBuilder) BuildFromAPIObject(obj *apis.CStorBackup) (*CStorBackup, error) {
	cb.obj.object = obj.DeepCopy()
	cb.obj.object.Name = obj.Spec.SnapName + "-" + obj.Spec.VolumeName
	cb = cb.Validate()
	return cb.obj, cb.err
}

// BuildFromAPIObjectName generates the CStorBackup object for given object name
func (cb *CStorBackupBuilder) BuildFromAPIObjectName(name string) (*CStorBackup, error) {
	obj, err := cb.obj.Get(name, cb.namespace)
	if err == nil {
		cb.obj.object = obj
		cb = cb.Validate()
	} else {
		errors.Wrapf(cb.err, "Failed to fetch backup{%s}: %s", name, err.Error())
	}
	return cb.obj, cb.err
}

// Validate is to validate generated CStorBackup object by current builder
func (cb *CStorBackupBuilder) Validate() *CStorBackupBuilder {
	if len(cb.predicatelist) != 0 {
		for _, pred := range cb.predicatelist {
			if !pred(cb.obj) {
				errors.Wrapf(cb.err, "Failed to run predicate {%v}", pred)
			}
		}
	}
	return cb
}
